name: LineageOTA

on:
  push:
    branches:
    - 'main'
    tags:
    - "*"
  pull_request:
    branches:
    - 'main'

env:
  _RELEASE_NAME: hoellenwesen/lineageota
  _RELEASE_VERSION: v0
  _BUILD_VERSION: "2.9.1.${{ github.run_number }}"
  _BUILD_BRANCH: "${{ github.ref }}"

jobs:
  LineageOTA:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Prepare environment
      run: ".github/workflows/prepare.ps1"
      shell: pwsh

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      uses: docker/build-push-action@v5
      with:
        tags: ghcr.io/hoellenwesen/${{ env._RELEASE_NAME }}:${{ env._RELEASE_VERSION }}

#    - name: Run Trivy vulnerability scanner
#      uses: aquasecurity/trivy-action@master
#      with:
#        image-ref: ${{ env._RELEASE_NAME }}:${{ env._RELEASE_VERSION }}
#        format: 'table'
#        exit-code: '1'
#        ignore-unfixed: true
#        vuln-type: 'os,library'
#        severity: 'CRITICAL,HIGH'

    - name: Push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ghcr.io/hoellenwesen/${{ env._RELEASE_NAME }}:${{ env._RELEASE_VERSION }}
